# Generated by Django 4.2.13 on 2025-01-09 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0004_character'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Character',
        ),
    ]
